### ISSUE TITLE
Network request failed

### ISSUE THREAD

**Issue by ilyabo** [tiensonqin/cljs-exponent#1]
First, thank you for working on this. It is an awesome project! 

I tried to create an app using the template (`lein new exponent expo-clj-test`) then run `npm install` , `lein figwheel` and `exp start --android`, enabled USB debugging on my Phone. Unfortunately the app doesn't work in Expo on my phone. I keep seeing red screen with `Network request failed`.  Same happens when trying to run fighweel in a Cursive REPL. What am I doing wrong?

![screenshot_20170317-144505](https://cloud.githubusercontent.com/assets/351828/24045868/d3752244-0b20-11e7-9be8-67a1fa4d0e3b.png)
![screenshot_20170317-144520](https://cloud.githubusercontent.com/assets/351828/24045872/d50c1bd0-0b20-11e7-95fe-098f9b9477b6.png)

The expo server also shows a warning `Warning: Invalid version of react-native for sdkVersion 14.0.0. Use github:exponent/react-native#sdk-14.0.0`. Could this be related to the issue?

Thanks in advance!

**Comment by tiensonqin** [comment]
@ilyabo Sorry for the late response, did latest template works for you?

**Comment by gabriel128** [comment]
I had the same issue, I was missing the `--lan` part in `exp start -a --lan`. I found it here https://github.com/tiensonqin/exponent-cljs-template/tree/master/resources/leiningen/new/exponent
