### ISSUE TITLE
Cannot import Expo Components

### ISSUE THREAD

**Issue by t4sk** [tiensonqin/cljs-exponent#5]
I cannot import Expo components, such as AppLoading.
I found out that AppLoading is a module under Expo.Components.AppLoading (not Expo.AppLoading).

```
cljs.user=> (require '[cljs-exponent.reagent :as rn])
nil
rncljs.user=> rn/app-loading
nil
```

In case someone else is having the same issue, here is a work around.

```
(def Expo (js/require "expo"))
(def Components (.-Components Expo))
(def AppLoading (.-AppLoading Components))

(def app-loading (r/adapt-react-class AppLoading))
```

**Comment by tiensonqin** [comment]
Now it works, sorry for the late response.
